#ifndef TYPE_ENUMS_H
#define TYPE_ENUMS_H

enum ValBoolTypeEnum {BOOLVAL_TRUE , BOOLVAL_FALSE};
enum opTypeEnum { OP_AND, OP_OR , OP_NOT  , OP_EQU ,
    OP_NEQ , OP_LEFTBIG , OP_RIGHTBIG , OP_LEFTBIGEQ , 
    OP_RIGHTBIGEQ};
enum TypeNameEnum { TYPE_VOID , TYPE_INT , TYPE_B ,
    TYPE_BYTE , TYPE_BOOL };
enum cmdTypeEnum {CMD_RETURN , CMD_IF , CMD_ELSE , CMD_WHILE , CMD_BREAK,
    CMD_CONTINUE , CMD_PRECOND , CMD_SECTION , CMD_COMMA , CMD_ASGN};

enum scopeValEnum {SCOPE_LPAREN , SCOPE_RPAREN , SCOPE_LBRACE
 , SCOPE_RBRACE};

#endif